### ISSUE TITLE
CheckpointException

### ISSUE THREAD

**Issue by RikusM** [CRaC/docs#22]
Good day, 

I checked out the jetty-app for a spring boot crac example demo but when trying to run the check point, I do get this error.

An exception during a checkpoint operation:
jdk.internal.crac.mirror.CheckpointException
    Suppressed: jdk.internal.crac.mirror.impl.CheckpointOpenFileException: FD fd=4 type=regular path=/var/lib/sss/mc/passwd
        at java.base/jdk.internal.crac.mirror.Core.translateJVMExceptions(Core.java:114)
        at java.base/jdk.internal.crac.mirror.Core.checkpointRestore1(Core.java:188)
        at java.base/jdk.internal.crac.mirror.Core.checkpointRestore(Core.java:286)
        at java.base/jdk.internal.crac.mirror.Core.checkpointRestoreInternal(Core.java:299)

Tried this https://mail.openjdk.org/pipermail/crac-dev/2022-January/000079.html but still not working.

**Comment by jankratochvil** [comment]
Do you have this fix in your build?
https://github.com/openjdk/crac/pull/137 = https://github.com/openjdk/crac/commit/16885f76b08630fedd9b3bb135f4de11847dca77

**Comment by RikusM** [comment]
Not yet do i need to build the jdk self or is there already a packaged version with this fix?

**Comment by jankratochvil** [comment]
Unfortunately this fix isn't yet in any published binary build.

**Comment by RikusM** [comment]
Hey just checking has this been fixed in any published binary build? @jankratochvil

**Comment by jankratochvil** [comment]
Unfortunately not yet but there should be a new build soon.

**Comment by RikusM** [comment]
Okay thank you, do you know when?
